version: "3"
services:
        jenkins:
                container_name: jenkins
                image: jenkins-ansible
                build:
                        context: jenkins-ansible
                ports:
                        - 8010:8080
                volumes:
                        - "$PWD/jenkins_home:/var/jenkins_home"
                networks:
                        - net
        remote_host:
                container_name: remote_host
                image: remote_host
                build:
                    context: remote-data
                networks:
                        - net
        db_host:
                container_name: db
                image: mysql:5.7
                environment:
                    - "MYSQL_ROOT_PASSWORD=1234"
                volumes:
                    - "$PWD/db_data:/var/lib/mysql"
                networks:
                    - net
networks:
        net:
